language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
    - mysql

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist --dev

script:
  - ./vendor/bin/phpunit --configuration phpunit_travis_mysql.xml --verbose --coverage-text test/
